### ISSUE TITLE
Track Zarr-Python Integration

### ISSUE THREAD

**Issue by quasiben** [rapidsai/kvikio#130]
Meta Issue to track work related to Zarr-KvikIO

Zarr PRs:
- https://github.com/zarr-developers/zarr-python/pull/934
- https://github.com/zarr-developers/zarr-python/pull/988
- https://github.com/zarr-developers/zarr-python/pull/1396

KvikIO PRs:
- https://github.com/rapidsai/kvikio/pull/129
- https://github.com/rapidsai/kvikio/pull/131

**Comment by madsbk** [comment]
I think everything has been done :)
