### ISSUE TITLE
[Question] kvikIO out-of-the-box support for S3 reads

### ISSUE THREAD

**Issue by sohomb91** [rapidsai/kvikio#142]
Hi Team,

Is there any out of the box  solution provided for object reads from S3 over any known sdk -- boto or azure for Cufile?

I could not find any ready solution for this hence decided to open a query here....

I am currently working an an infra project to test the performances of storage devices -- and a part of that work involves object reads from S3.
I have tried downloading the S3 object and then go for Cufile reads, however, it seems somewhat like taking a detour to reach the destination -- and I am mostly concerned with the performance implications over the extra code!

Therefore I wanted to know if there are any solutions provided in kvikIO for such a use case? If not, maybe you could suggest an alternative to approaching the problem without going through the download & read path?

***N.B.:*** I have also played around with [DALI](https://github.com/NVIDIA/DALI), so open to any suggestions, if it involves [DALI](https://github.com/NVIDIA/DALI) as well.... 

Many thanks in advance.

**Comment by madsbk** [comment]
Sorry @sohomb91, I do not have good alternative to the download & read path :/

Currently, GDS is not available on Amazon S3 so cuFile will not be of any help. However, if there is interest, we could implement Amazon S3 support in KvikIO. Such as implementation would probably use a  download & read path approach at first but could transit to use GDS when it becomes available. Furthermore, it could be used as a backend to Zarr's S3 support.

**Comment by sohomb91** [comment]
Got it, yeah that kind of made sense since GDS wont be available on S3 -- I will go forward with my original implementation then...!
Many thanks for confirming this.
