### ISSUE TITLE
Cannot Install Kvikio using conda

### ISSUE THREAD

**Issue by tjk9501** [rapidsai/kvikio#148]
Hello!

I tried to install Kvikio using the following code:
```
conda install -c rapidsai -c conda-forge kvikio
```
but anaconda said it couldn't find the package, I am using a windows 10 system, can anyone help me resolve this problem? Thank you!

**Comment by tjk9501** [comment]
In an already existed anaconda environment.

**Comment by madsbk** [comment]
@tjk9501 are you using Windows Subsystem for Linux (WSL)? Or native windows?

**Comment by madsbk** [comment]
Please re-open fix this is still an issue
