### ISSUE TITLE
Use `rapids-cython` & other more recent best practices

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/kvikio#186]
Would it make sense to start using `rapids-cython` here as in cuDF?

https://github.com/rapidsai/cudf/blob/766af666575b5db6f265e1fbf6466ccfd46eae30/python/cudf/CMakeLists.txt#L72

Any other best practices we should adopt here to modernize our scikit-build/CMake files?

Maybe some of these items are worth addressing ( https://github.com/rapidsai/kvikio/pull/58#discussion_r845608125 )

**Comment by jakirkham** [comment]
cc @vyasr @robertmaynard

**Comment by vyasr** [comment]
Yes it would be good to use `rapids-cython` and replace https://github.com/rapidsai/kvikio/blob/branch-23.04/python/cmake/kvikio_python_helpers.cmake

**Comment by vyasr** [comment]
There are numerous other changes that have been made across RAPIDS that are somewhat related, such as moving away from setup.py towards pyproject.toml, using `rapids-dependency-file-generator`, and removing versioneer. Some of these are more relevant to scikit-build than others; the pyproject.toml migration will eventually be necessary to use the modern incarnation of scikit-build, which is a purely pyproject.toml, PEP 517-based builder.
