### ISSUE TITLE
Conda Package

### ISSUE THREAD

**Issue by madsbk** [rapidsai/kvikio#2]
We should create Conda packages, both regular and nightly and releases.

@quasiben and @jakirkham I am hope this is something you guys can help with? :)

**Comment by quasiben** [comment]
@madsbk do you think it's necessary to build a libkvikio conda package as well as the Python package or is one large package enough ?

**Comment by madsbk** [comment]
One conda package of the Python library should be enough. 
Notice, the C++ library is header-only so there isn't any compiled library such as `libkvikio.so`

**Comment by jakirkham** [comment]
We build a C++ & Python package for RMM, which is also header only.

**Comment by madsbk** [comment]
> We build a C++ & Python package for RMM, which is also header only.

You are right, we need a Conda package for the C++ header files to make it easy for projects like cuCIM and cuDF to use the C++ API.
