### ISSUE TITLE
Work around scikit-build `include_package_data` bug in `legate/setup.py`

### ISSUE THREAD

**Issue by wence-** [rapidsai/kvikio#233]
Not critical since kvikio doesn't have wheels, but scikit-build has bugs with `include_package_data` so specifying `package_data` explicitly (like in the non-legate setup.py) is safer. That said I don't see wheels happening for legate-kvikio anytime soon so it's mostly just to be safe.

_Originally posted by @vyasr in https://github.com/rapidsai/kvikio/pull/232#discussion_r1218742293_

**Comment by madsbk** [comment]
`legate/setup.py` has been removed
