### ISSUE TITLE
A context for Codec `encode_batch` and `decode_batch`

### ISSUE THREAD

**Issue by madsbk** [rapidsai/kvikio#251]
Before proposing the new `encode_batch` and `decode_batch` API  (https://github.com/rapidsai/kvikio/issues/248) to [numcodecs Codec](https://numcodecs.readthedocs.io/en/stable/abc.html), I think we should introduce a new context argument similar to Zarr's [`Context`](https://github.com/zarr-developers/zarr-python/blob/main/zarr/context.py).

This way, we can use the `meta_array` option to specify the output memory type of `encode_batch` and `decode_batch`.

cc. @Alexey-Kamenev

**Comment by akshaysubr** [comment]
Agreed, this would indeed be very valuable!

**Comment by madsbk** [comment]
Closing this issue, I don't think we need this for Zarr V3
