### ISSUE TITLE
Notebooks with old API

### ISSUE THREAD

**Issue by loliverhennigh** [rapidsai/kvikio#270]
The notebook here uses the old API for compressors
https://github.com/rapidsai/kvikio/blob/branch-23.10/notebooks/nvcomp_vs_zarr_lz4.ipynb
```python
    compressor = kvikio.nvcomp.CascadedCompressor(data_gpu.dtype)
```
Love the project!

**Comment by madsbk** [comment]
Thanks @loliverhennigh, https://github.com/rapidsai/kvikio/pull/294 should fix the issue
