### ISSUE TITLE
single-node-io.py sample fails inside a docker container

### ISSUE THREAD

**Issue by hjiang520** [rapidsai/kvikio#283]
Hi,

I met an error when tried to run the single-node-io.py using GDS in a docker container:
```
Roundtrip benchmark
----------------------------------
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
   WARNING - cuFile compat mode
         GDS not enabled
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
GPU               | NVIDIA RTX A5000 (dev #1)
GPU Memory Total  | 23.99 GiB
BAR1 Memory Total | 32.00 GiB
GDS driver        | N/A (Compatibility Mode)
GDS config.json   | /usr/local/cuda-12.2/gds/cufile.json
----------------------------------
nbytes            | 10485760 bytes (10.00 MiB)
4K aligned        | True
pre-reg-buf       | True
directory         | /tmp/tmp0liejz2p
nthreads          | 1
nruns             | 1
==================================
Traceback (most recent call last):
  File "/root/kvikio/python/benchmarks/single-node-io.py", line 441, in <module>
    main(args)
  File "/root/kvikio/python/benchmarks/single-node-io.py", line 338, in main
    read, write = API[api](args)
  File "/root/kvikio/python/benchmarks/single-node-io.py", line 51, in run_cufile
    f = kvikio.CuFile(file_path, flags="w")
  File "/root/mambaforge/envs/kvikio-dev/lib/python3.10/site-packages/kvikio/cufile.py", line 67, in __init__
    self._handle = libkvikio.CuFile(file, flags)
  File "libkvikio.pyx", line 110, in kvikio._lib.libkvikio.CuFile.__init__
RuntimeError: cuFile error at: /root/kvikio/cpp/include/kvikio/file_handle.hpp:177: internal error
```

It seems that the low-level GDS error message did not get propagated through kvikio API. The line points to the cuFile API "cuFileHandleRegister"..

is there any way I can get the error code of "cuFileHandleRegister" here? 

Do I need to configure and install GDS on my local machine before trying this sample in a docker container?

**Comment by madsbk** [comment]
cuFile should write a `cufile.log` file in the current directory, which hopefully contains more info. 

Also, to rule out bugs in KvikIO, try running `KVIKIO_COMPAT_MODE=ON python single-node-io.py`, which is running without using cuFile and GDS.

I am not sure about the current status of running cuFile and GDS in a docker container but I think it should work. @tell-rebanta do you know?

**Comment by hjiang520** [comment]
Hi @madsbk ,

I see the following info in the cufile.log:
" 21-09-2023 16:18:27:848 [pid=1844 tid=1844] NOTICE  cufio-drv:720 running in compatible mode
 21-09-2023 16:18:30:53 [pid=1844 tid=1844] ERROR  cufio-fs:322 error creating udev_device for block device dev_no: 0:64
 21-09-2023 16:18:30:53 [pid=1844 tid=1844] ERROR  cufio-fs:733 error getting volume attributes error for device: dev_no: 0:64
 21-09-2023 16:18:30:53 [pid=1844 tid=1844] ERROR  cufio-obj:174 unable to get volume attributes for fd 67
 21-09-2023 16:18:30:53 [pid=1844 tid=1844] ERROR  cufio:1565 cuFileHandleRegister error, failed to allocate file object
 21-09-2023 16:18:30:54 [pid=1844 tid=1844] ERROR  cufio:1593 cuFileHandleRegister error: internal error
"
If I set the kvikio to compat mode, it runs fine "`kvikio.defaults.compat_mode_reset(1);`"
but by default, this code will identify itself as the "GDS is not available", so I am guessing that I must miss some steps to set up GDS before trying this kvikio APIs in a docker container:
```
    elif not props.is_gds_available:
        print("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
        print("   WARNING - cuFile compat mode   ")
        print("         GDS not enabled          ")
        print("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
```

**Comment by tell-rebanta** [comment]
Running cufile and GDS through docker container is supported. However, in this case, looks like GDS is not installed. I would suggest  you to go through the installation process (https://docs.nvidia.com/gpudirect-storage/troubleshooting-guide/index.html) and make sure GDS is installed.

**Comment by madsbk** [comment]
Please re-open if this is still an issue
