### ISSUE TITLE
Error when resetting number of threads using kvikio.

### ISSUE THREAD

**Issue by jcfaracco** [rapidsai/kvikio#307]
Hello everybody!

I'm using RAPIDS 23.08 and consequently kvikio 23.08 as well.

I'm seeing a weird issue when I try to reset the number of threads. Right now the value is 1, but I would like to increase that. See below the traceback of my code:

```python
Traceback (most recent call last):
  File "attributes.py", line 139, in <module>
    kvikio.thread_pool.num_threads_reset(72)
  File "/opt/conda/lib/python3.10/site-packages/kvikio/thread_pool.py", line 24, in num_threads_reset
    libkvikio.thread_pool_num_threads_reset(nthreads)
AttributeError: module 'kvikio._lib.libkvikio' has no attribute 'thread_pool_num_threads_reset'. Did you mean: 'thread_pool_nthreads_reset'?
```

If I try to move to the suggestion, I got a different one:

```python
Traceback (most recent call last):
  File "attributes.py", line 139, in <module>
    kvikio.thread_pool.nthreads_reset(72)
AttributeError: module 'kvikio.thread_pool' has no attribute 'nthreads_reset'. Did you mean: 'num_threads_reset'?
```

Looks like there is a mismatch between kvikio and libkvikio.

**Comment by madsbk** [comment]
Thanks for reporting this @jcfaracco.  
The `thread_pool` module should have been removed years ago.  Use should be able to use the default module instead:
```python
kvikio.defaults.num_threads_reset()
kvikio.defaults.get_num_threads()
```
xref: https://github.com/rapidsai/kvikio/pull/308
