### ISSUE TITLE
Support aarch64 + libcufile

### ISSUE THREAD

**Issue by bdice** [rapidsai/kvikio#339]
As of CUDA 12.2, there is a libcufile library for aarch64. In #328, we updated to CUDA 12.2 but decided to hold off on changing behavior around libcufile on aarch64. Because kvikio dlopens libcufile, it may be possible to have a runtime check that disables libcufile support on aarch64 with CUDA < 12.2 (or if the library is not installed). I haven't investigated this very far, but wanted to open this issue for tracking purposes.

See also: https://github.com/rapidsai/kvikio/pull/328#pullrequestreview-1873354307

We wouldn't be able to add `libcufile` as a hard dependency on aarch64 until dropping CUDA 12.0 / 12.1, but it should be possible to build a package that supports libcufile if it is installed by the user.

cc: @vyasr, thanks for the proposal. This sounds plausible.

**Comment by vyasr** [comment]
Thanks for opening the issue Bradley. I'm pretty sure this is the right long-term answer here, but it's not a blocker for us getting CUDA 12.2 done.
