### ISSUE TITLE
pip availability

### ISSUE THREAD

**Issue by ivirshup** [rapidsai/kvikio#367]
It would be nice if this were available via pip as well as conda. I'm working with an environment right now where we've managed to get most other libraries working via pip (some needed `--extra-index-url=https://pypi.nvidia.com`), then realized we've now got to add kvikio.

**Comment by jakirkham** [comment]
Thanks Isaac! 🙏

This is a known issue. Please see https://github.com/rapidsai/kvikio/issues/250

Going to go ahead and close as a duplicate

**Comment by ivirshup** [comment]
Ah, sorry managed to miss that!

**Comment by jakirkham** [comment]
All good. It's helpful to know this matters to you 🙂
