### ISSUE TITLE
ImportError: libnvcomp.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by saishashank85** [rapidsai/kvikio#368]
I have installed nvcomp following instruction from here : https://stackoverflow.com/questions/72957125/guide-for-installation-of-nvidia-s-nvcomp-and-running-of-its-accompanying-exampl

I am building kvikio from source. 

I an encountering this error while importing kvikio 

root@n2na6fnh47:/notebooks/git/kvikio/python# pytest tests/
ImportError while loading conftest '/notebooks/git/kvikio/python/tests/conftest.py'.
tests/conftest.py:11: in <module>
    import kvikio.defaults
/usr/local/lib/python3.11/dist-packages/kvikio/__init__.py:4: in <module>
    from ._lib import libkvikio  # type: ignore
E   ImportError: libnvcomp.so: cannot open shared object file: No such file or directory

**Comment by jakirkham** [comment]
Could you please share the exact steps run to install nvCOMP?

**Comment by madsbk** [comment]
Please re-open if this is still an issue
