### ISSUE TITLE
Incompatibility with ARM

### ISSUE THREAD

**Issue by Marcus-M1999** [rapidsai/kvikio#393]
Hello,

It seems that there is an incompatibility with the ARM architecture. Is there anyway that this could be fixed? I was able to get this repo running by having a colleague build from source, however conda install from the stable and nightly repo doesn't work.
Specs:
 NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4 GPU: A6000

**Comment by madsbk** [comment]
What errors are  you seeing? 
We do run CI tests on ARM; it is supposed to work :)

**Comment by Marcus-M1999** [comment]
The kvikio.defaults.compat_mode() returns true even though the cufile.json is set to false. I tested the read & write times both are slower than or equal to the time it takes to save a CPU array. I'm testing by saving a sin wave in a cupy array with the blow code:
`cp.sin(cp.arange(0, 100000000, 0.1))`

**Comment by jakirkham** [comment]
Is this still an issue after our offline discussion, Marcus?

**Comment by Marcus-M1999** [comment]
The code seems to be working, there is a slight speed up for this workload. The only "bug" I would say is that we could only get it working after building the library from source. When trying to install via pip or conda it wouldn't work properly. I'm not sure what the issue could be, if it's working on your system then I'll try to dig deeper into the issue on my IGX.

**Comment by jakirkham** [comment]
It might be worth retrying the pip & conda installs. AIUI there were a number of changes that occurred to the system between initially testing these and switching to building from source to test. It would be good to determine whether the system changes had any effect on the binary installs

**Comment by jakirkham** [comment]
In 24.08 we enabled cuFile on ARM ( https://github.com/rapidsai/kvikio/pull/405 ), which was previously disabled

Does that help?
