### ISSUE TITLE
Static linking of cufile

### ISSUE THREAD

**Issue by madsbk** [rapidsai/kvikio#4]
I am trying to statically link cufile (`libcufile_static.a`) but it fails when calling the cuda api. Am I doing something stupid?

##### `mylib.cpp`
```c++
#include <iostream>
#include <cassert>
#include <nvml.h>
#include <cuda.h>
#include <cuda_runtime_api.h>

using namespace std;

void test() {
    cout << "test()" << endl;
    nvmlReturn_t e1 = nvmlInit();
    assert(e1 == NVML_SUCCESS);

    cudaError e2 = cudaSetDevice(0);
    assert(e2 == cudaSuccess);

    CUdevice cu_dev{};
    CUresult e3 = cuCtxGetDevice(&cu_dev);
    cout << "cuCtxGetDevice(): " << e3 << endl;
    assert(e3 == CUDA_SUCCESS);
}
```

##### `myapp.cpp`
```c++
void test();

int main()
{
    test();
}
```

##### `build.sh`
```bash
set -e

CUFILE=/usr/local/cuda/lib64/libcufile_static.a
#CUFILE=

g++ -c -O1 -g -std=gnu++17 -fPIC -I /usr/local/cuda/include mylib.cpp

g++ -shared -std=gnu++17 -O1 -g mylib.o $CUFILE \
-L/usr/local/cuda/lib64 -lcudart -lnvidia-ml -lcuda -o mylib.so

g++ myapp.cpp  -std=gnu++17 -O1 -g  -Wl,-rpath,/usr/local/cuda/lib64 -Wl,-rpath,. mylib.so -o myapp

./myapp
```
 
Placing the three files in a folder and running `sh build.sh` produces:
```
$ sh build.sh 
test()
cuCtxGetDevice(): 999
myapp: mylib.cpp:21: void test(): Assertion `e3 == CUDA_SUCCESS' failed.
Aborted (core dumped)
```

Now, if I do dynamic linking instead by setting `CUFILE=` and adding `-lcufile` in the build script, it works:
```
$ sh build.sh 
test()
cuCtxGetDevice(): 0
```

**Comment by madsbk** [comment]
I think I found the issue. When static linking to `libcufile_static.a`, we have to call `cuInit(0)` before using the Driver API explicitly and cannot rely on `cudaSetDevice(0)` to do the initialization.
However, with dynamic linking the following works without the `cuInit(0)` call, which is also the case when static linking to other cuda libraries such as `libcufft_static.a` and `libblas_static.a`.

```c++
#include <cassert>
#include <iostream>
#include <cuda.h>
#include <cuda_runtime_api.h>

using namespace std;

void test() {
    // Is required when static linking libcufile_static.a.
    // This is NOT required when not static linking cufile or
    // when static linking to other libraries like libcufft_static.a
    cuInit(0);

    cudaError e1 = cudaSetDevice(0);
    assert(e1 == cudaSuccess);

    CUdevice cu_dev{};
    CUresult e2 = cuCtxGetDevice(&cu_dev);
    cout << "cuCtxGetDevice(): " << e2 << endl;
    assert(e2 == CUDA_SUCCESS);
}
```

**Comment by jakirkham** [comment]
Something to think about is how this behaves around forking. Believe we can only call `cuInit` after forking.

**Comment by madsbk** [comment]
> Something to think about is how this behaves around forking. Believe we can only call `cuInit` after forking.

Good point, in https://github.com/rapidsai/kvikio/pull/6 the `cuInit` call is delayed until the NVML API is used.
