### ISSUE TITLE
How Do I Pronounce kvikio?

### ISSUE THREAD

**Issue by K-Wu** [rapidsai/kvikio#428]
Hi there,

Thank you for the great package. I am using it in my project and introducing it to others. May I know how I shall pronounce kvikio?

Best Regards,
Kun

**Comment by jakirkham** [comment]
Good question

[Kvik is a Danish word]( https://en.m.wiktionary.org/wiki/kvik#Danish ). It sounds similar to the English word "quick" (and they have similar meanings)

IO is just meaning the typical computer science term, input/output. The letters are just sounded out individually

So altogether it would be Kvik-I-O

Does that make sense?

**Comment by K-Wu** [comment]
Got it. Thank you for the explanation! I appreciate it.

**Comment by jakirkham** [comment]
Maybe this also helps: https://github.com/rapidsai/kvikio/pull/480
