### ISSUE TITLE
Allow task tuning within the same process

### ISSUE THREAD

**Issue by GregoryKimball** [rapidsai/kvikio#451]
When benchmarking with the `KVIKIO_TASK_SIZE` and `KVIKIO_NTHREADS`, I observed that changes to these variable don't seem to take effect if kvikIO has already been initialized in a process. For instance, if I loop over `KVIKIO_NTHREADS` in python, all of the reads seem to use the default values. However, if I set  `KVIKIO_TASK_SIZE` and `KVIKIO_NTHREADS` before launching the python process, then they appear to work as intended.

Is it possible for `KVIKIO_TASK_SIZE` and `KVIKIO_NTHREADS` to be updated dynamically within a process?

**Comment by wence-** [comment]
You should use the programmatic interface rather than relying on environment variables:

```
import kvikio.defaults

kvikio.defaults.num_threads_reset(required_number_of_threads)

kvikio.defaults.task_size_reset(required_task_size)
```
