### ISSUE TITLE
Verify behavior of `KVIKIO_BOUNCE_BUFFER_SIZE`

### ISSUE THREAD

**Issue by GregoryKimball** [rapidsai/kvikio#452]
When attempting to analyze large task sizes, it appears that the size of a copy is always capped at 16 MiB. 

Even with `KVIKIO_BOUNCE_BUFFER_SIZE` of 40 MB and `KVIKIO_TASK_SIZE` of 40 MB, I observe copies capped at ~16 MiB in the profile. Is there a way to enable larger task sizes?

![Image](https://github.com/user-attachments/assets/e5760f8c-7eeb-457b-9c79-878108f96ab7)

**Comment by wence-** [comment]
Does your kvikio contain 0b8525a ?

**Comment by madsbk** [comment]
There was a bug with the bounce buffer, which should be fixed in https://github.com/rapidsai/kvikio/pull/454. 
Locally, nsys now reports correct memcpys, which should be the lowest of `KVIKIO_BOUNCE_BUFFER_SIZE` and `KVIKIO_TASK_SIZE`.
