### ISSUE TITLE
Nvidia GPUDirect Storage support

### ISSUE THREAD

**Issue by kamikaze** [rapidsai/kvikio#63]
Hello. I decided to ask for help here, because I'm lost. GDS seems very unfriendly to get working. Do you have any instructions on how to get it working? As a developes how do you get it? Are you using ancient ubuntu 20.04? Thanks

**Comment by madsbk** [comment]
> Are you using ancient ubuntu 20.04? 

Yes, the newest official CUDA package for Ubuntu is [20.04](https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&Distribution=Ubuntu&target_version=20.04&target_type=deb_local). Alternatively, you can use the [NVIDIA Magnum IO Developer Environment](https://github.com/NVIDIA/MagnumIO/blob/main/dev-env/README.md).

But notice, KvikIO doesn't require GDS, which makes it possible to do development in must linux environments (incl. WSL). KvikIO will look for `libcufile.so` at runtime and if it isn't found, KvikIO uses its own IO implementation.

**Comment by madsbk** [comment]
Closing this issue, @kamikaze please re-open if this is still an issue.
