### ISSUE TITLE
Writing a mix of host & device frames doesn't work

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/kvikio#76]
Currently if a user tries to write a mixture of host & device frames, this doesn't work as the following error will show up for any host frames

https://github.com/rapidsai/kvikio/blob/7a43759ae8638c17a02f68f4e8d777e52480fe37/python/kvikio/_lib/libkvikio.pyx#L86

This matters as using KvikIO in Distributed & Dask-CUDA will depend on handling some host frames along the way while [reading]( https://github.com/rapidsai/dask-cuda/blob/8df1507490d5c89ba2d880aece5eb508970b3433/dask_cuda/disk_io.py#L209-L213 ) and [writing]( https://github.com/rapidsai/dask-cuda/blob/8df1507490d5c89ba2d880aece5eb508970b3433/dask_cuda/disk_io.py#L166-L171 ).

Maybe there could be some kind of fallback to handle host memory in these cases?

**Comment by madsbk** [comment]
> Maybe there could be some kind of fallback to handle host memory in these cases?

Agree, I think KvikIO should support IO of host buffers seamlessly. This should also use [`parallel_io()`](https://github.com/rapidsai/kvikio/blob/branch-22.06/cpp/include/kvikio/parallel_operation.hpp#L43) for good performance.
