### ISSUE TITLE
Adding multiline/IOV APIs

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/kvikio#77]
In some cases a user needs to write a `list` of binary data (like using [`writelines`]( https://docs.python.org/3/library/io.html#io.IOBase.writelines )). It would be useful to have an API like this when working with multiple frames.

Similarly it might be handy to have some kind of API for reading in data to multiple buffers. There is not exactly an analogous API in Python. Though [`socket.recvmsg_into`]( https://docs.python.org/3/library/socket.html#socket.socket.recvmsg_into ) is close (so might be a starting point).

This can be particularly helpful if the GIL is released in the background as there can be one API call that releases the GIL as opposed to a couple in rapid succession.

**Comment by madsbk** [comment]
I think this is possible using the non-blocking API, `pread` and `pwrite`. At least, we do release the GIL when calling `IOFuture.get()`: 
https://github.com/rapidsai/kvikio/blob/branch-23.08/python/kvikio/_lib/libkvikio.pyx#L23

**Comment by jakirkham** [comment]
Interesting was thinking more of things like [`preadv`]( https://linux.die.net/man/2/preadv ) & [`pwritev`]( https://linux.die.net/man/2/pwritev )

This way one could give a `list` of [`Array`]( https://github.com/rapidsai/kvikio/blob/1ffe8b1f6fe10ad74e63463f7cce7ea04c7a828b/python/kvikio/_lib/arr.pyx#L66 )-like objects to KvikIO, which could in turn covert them into an [`iovec`]( https://man7.org/linux/man-pages/man3/iovec.3type.html )-like object under-the-hood

**Comment by madsbk** [comment]
I think that is a good idea but I would suggest that `preadv` and `pwritev` just returns a list of futures. Then we can have a `waitall` functions that waits on all futures in a list.
