### ISSUE TITLE
An ERROR OCCURS AFTER CONDA INSTALL

### ISSUE THREAD

**Issue by Weigaa** [rapidsai/kvikio#88]
We use this command to install kvikio as follows:
`conda create -n kvikio_env -c rapidsai-nightly -c conda-forge python=3.8 cudatoolkit=11.5 kvikio`
But When I use test code, an error occurs:

Some environmental configuration information is as follows.
`RuntimeError: libcuda.so: cannot open shared object file: No such file or directory`

But we can find the file in：
`/usr/local/cuda-11.7/targets/x86_64-linux/lib/stubs/`

My Cuda version is 11.7 and my GPU is P100.
Linux kernel is 5.4.0-70, gcc and g++ both version 11.

And the environment is:
```
export PATH=$PATH:/root/anaconda3/bin

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-11.7/lib64
export PATH=$PATH:/usr/local/cuda-11.7/bin
export CUDA_HOME=$CUDA_HOME:/usr/local/cuda-11.7
export CUFILE_PATH="/usr/local/cuda-11.7/targets/x86_64-linux/lib/"
export DALI_EXTRA_PATH="/mnt/optane/wjtest/DALI_extra/"

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/root/anaconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/root/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/root/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/root/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<
source activate
```

**Comment by quasiben** [comment]
Are you also using Docker or are you running on baremetal ?

**Comment by Weigaa** [comment]
> Are you also using Docker or are you running on baremetal ?
Thanks, it's baremetal.
We solved these errors after reinstalling Nvidia drivers and Cuda toolkits (including nvidia_fs et al.).
