### ISSUE TITLE
inconsistency of reset function names in kvikio.defaults

### ISSUE THREAD

**Issue by grlee77** [rapidsai/kvikio#92]
It seems a bit counterintuitive that there is
`reset_num_threads`
`reset_task_size`
but
`compat_mode_reset`

For consistency, I would have expected the last one to be `reset_compat_mode`. Do you think this is worth changing via a deprecation cycle?

The C++ API consistently has all three functions in a form **ending** in `_reset`, but if we did that on the Python side we would have to change two of the existing functions.

**Comment by madsbk** [comment]
I think this is a very good idea! 

Let's change all of them to end with `_reset` in `branch-22.10`
