### ISSUE TITLE
Example of Zarr access from C++?

### ISSUE THREAD

**Issue by dzenanz** [rapidsai/kvikio#93]
Is there an example of using Zarr IO from C++? Is arbitrary metadata supported? Is there an example of that? Does `kvikio` even offer Zarr IO? After #82 is integrated, would it be possible to read/write Zarr directly from the host memory?

**Comment by madsbk** [comment]
No, KvikIO doesn't implement Zarr in C++ :/

We are working on making [Zarr-Python](https://github.com/zarr-developers/zarr-python) support [any kind of arrays](https://github.com/zarr-developers/zarr-python/pull/934) and then use it to create Zarr arrays of CuPy chunks that use KvikIO seamlessly.

**Comment by dzenanz** [comment]
Thanks for the response.
